services:
  mongodb_container:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass 
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
   
volumes:
  mongodb_data_container:
