services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: yeab
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/posgresql/data
  mongodb:
    image: mongo
    ports:
      - "2717:27017"
    volumes: 
      - /var/lib/mongodb/data
volumes:
  pgdata:
  mongodb_data_container:
